name: Bug Report
description: File a bug report
title: "[Bug]: <add a short description here>"
labels: ["bug"]
assignees:
  - avoonix
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce the Problem
      description: How can this be reproduced?
    validations:
      required: false
