name: Feature Request
description: Suggest an idea
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - avoonix
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest new features!
  - type: textarea
    id: feature
    attributes:
      label: Description
      description: Describe the feature
    validations:
      required: true
