name: Feature Request
description: Suggest an idea
title: "[Feature]: <add a short description here>"
labels: ["enhancement"]
assignees:
  - avoonix
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest new features!
  - type: textarea
    id: feature
    attributes:
      label: Description
      description: Describe the feature. If you want to suggest multiple features, create a separate issue for each of them.
    validations:
      required: true
